<?php

function myhook_menu () {
   $items['font_page'] = array(
    'page callback' => 'fron_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

function fron_page() {
  return theme('font_page_template');
}

function myhook_theme() {
  $themes = array(
    'font_page_template' => array(
      'template' => 'fontpage',
      'arguments' => array('xxx' => 'ddd'),
    ),
  );
  return $themes;
}

function myhook_form_contact_site_form_alter(&$form, $form_state) {
    $form['subject']['#access'] = FALSE;
    $form['name']['#access'] = FALSE;
    /*
    $form['actions']['submit']['#ajax'] = array (
      'callback' => '_handle_form_submit',
      'effect' => 'fade',
    );
    */
}
function _handle_form_submit ($form, $form_state) {

}
